# Generated by Django 3.0.8 on 2020-07-14 11:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200714_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 14, 11, 2, 56, 459764, tzinfo=utc), verbose_name='date published'),
        ),
    ]
