# Generated by Django 3.0.8 on 2020-08-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200716_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
